controllers:
  resource: ../src/Controller/
  type: annotation


home:
 path: /home
 controller: App\Controller\HomeController::index
 
 
new:
 path: /new
 controller: App\Controller\NewController::index